#!/bin/sh -e
#
# 2012 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

config=/etc/postfix/master.cf
entry="${__object:?}/files/entry"
state_should=$(cat "${__object:?}/parameter/state")

if test ! -s "${__object:?}/explorer/entry"
then
   state_is='absent'
else
   state_is=$(diff -q "${entry}" "${__object:?}/explorer/entry" >/dev/null \
      && echo present \
      || echo changed)
fi

if test "${state_should}" = "${state_is}"
then
   # Nothing to do, move along
   exit 0
fi


remove_entry() {
   # NOTE: keep variables in sync in manifest/explorer/gencode-*
   prefix="#cdist:${__object_name:?}"
   suffix="#/cdist:${__object_name:?}"
   cat <<DONE
tmpfile=\$(mktemp ${config}.cdist.XXXXXXXXXX)
# preserve ownership and permissions of existing file
cp -p "${config}" "\${tmpfile}"
awk -v prefix="${prefix}" -v suffix="${suffix}" '
{
   if (index(\$0,prefix)) {
      triggered=1
   }
   if (triggered) {
      if (index(\$0,suffix)) {
         triggered=0
      }
   } else {
      print
   }
}' "${config}" >"\${tmpfile}"
mv -f "\${tmpfile}" "${config}"
DONE
}

case ${state_should}
in
   (present)
      if test "${state_is}" = 'changed'
      then
         remove_entry
      fi
      cat <<EOF
cat >>"${config}" <<'CONFIG_EOF'
$(cat "${entry}")
CONFIG_EOF
EOF
      ;;
   (absent)
      remove_entry
      ;;
esac
