#!/bin/sh
#
# 2012-2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current value of the Postfix configuration option.
#

if test -f "${__object:?}/parameter/key"
then
	key=$(cat "${__object:?}/parameter/key")
else
	key=${__object_id:?}
fi

postconf -h "${key}"
